config/routes.rb
Rails.application.routes.draw do

  get 'home/index'

  root 'home#index'

  concern :history do
    get :history, :on => :member
  end

  resources :contacts, concerns: :history
  resources :accounts, concerns: :history

  match "*path_does_not_exists" => "errors#raise_action_dispatch_exception", via: :all

end

app/models/contact.rb
# == Schema Information
#
# Table name: contacts
#
#  id         :integer          not null, primary key
#  last_name  :string(255)
#  first_name :string(255)
#  email      :string(255)
#  tel_number :string(255)
#  fax_number :string(255)
#  address    :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Contact < ActiveRecord::Base
  #association---------------------------------------------------------
  has_many :contact_histories
  has_many :account_contacts
  has_many :accounts, :through => :account_contacts

  #validation---------------------------------------------------------
  include ActiveModel::Validations
  validates_with ContactValidator

  validates :last_name,
    length: { maximum: 50 }
  validates :first_name,
    length: { maximum: 50 }
  validates :email,
    email: true,
    exclusion: { in: %w(admin@example.com superuser@example.com) } #TODO:ベタ書きはよくない
  validates :tel_number,
    tel_number: true,
    length: { maximum: 18 }
  validates :fax_number,
    fax_number: true,
    length: { maximum: 18 }
  validates :address,
    length: { maximum: 255 }

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]
  before_action :set_related_account, only: [:show, :edit]

  # GET /contacts
  # GET /contacts.json
  def index
    if params[:keyword] && params[:keyword].present?
      cond = "%#{params[:keyword]}%"
      @all_contacts = Contact.where("last_name LIKE ? OR first_name LIKE ?", cond, cond)
      @contacts = @all_contacts.page(params[:page])
    else
      @all_contacts = Contact.all
      @contacts = @all_contacts.page(params[:page])
    end
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/1/histories
  def history
    @contact = Contact.find(params[:id])
    @histories = ContactHistory.of(params[:id])
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create

    #TODO:associationも含めnewしたい

    @contact = Contact.new(contact_params)
    ActiveRecord::Base.transaction{
      respond_to do |format|
        if @contact.save

          @ac = @contact.account_contacts.new(
            contact_id: Contact.last.id,
            account_id: params[:account_contact][:account_id]
          )

          @ac.save

          format.html { redirect_to @contact, notice: I18n.t("models.contact.notice.create_success") }
          format.json { render :show, status: :created, location: @contact }
        else
          #TODO:rollback時の処理がない
          format.html { render :new }
          format.json { render json: @contact.errors, status: :unprocessable_entity }
        end
      end
    }

  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update

    @contact_history = ContactHistory.new(
      contact_id: @contact.id,
      last_name: @contact.last_name,
      first_name: @contact.first_name,
      email: @contact.email,
      tel_number: @contact.tel_number,
      fax_number: @contact.fax_number,
      address: @contact.address
    )

    ActiveRecord::Base.transaction do
      #TODO:rollback時の処理がない
      respond_to do |format|
        if @contact.update(contact_params) && @contact_history.save

          #TODO:変更履歴保持にはAccountContactHistoryも必要
          #TODO:複数テーブルにまたがって、いつの版のレコードか識別するためのキーが必要

          format.html { redirect_to @contact, notice: I18n.t("models.contact.notice.update_success") }
          format.json { render :show, status: :ok, location: @contact }
        else
          format.html { render :edit }
          format.json { render json: @contact.errors, status: :unprocessable_entity }
        end
      end
    end

  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: I18n.t("models.contact.notice.destroy_success") }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
      @ac = AccountContact.where(contact_id:params[:id]) #ない場合もある
    end

    def set_related_account
      @belonging = Account.which_this_contact_belongs_to(params[:id]).first
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:last_name, :first_name, :email, :tel_number, :fax_number, :address)
    end

    def account_contact_params
      params.require(:account_contact).permit(:account_id)
    end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_form.html.erb
<script>
  function focusOnFirstInput(){
    var e = document.getElementById("contact_last_name")
    e.focus()
  }
  document.body.onload=focusOnFirstInput;
</script>


<% if @contact.errors.any? %>
  <div class="card" id="error_explanation">
    <% @contact.errors.full_messages.each do |message| %>
      <ul class="table_view">
        <li class="table_view-cell">
          <%= message %>
        </li>
      </ul>
    <% end %>
  </div>
<% end %>

<%= form_for @contact, html: {class: "input-group"} do |f| %>

  <div class="input-row">
    <%= f.label I18n.t('models.contact.attributes.last_name') %>
    <%= f.text_field :last_name %>
  </div>

  <div class="input-row">
    <%= f.label I18n.t('models.contact.attributes.first_name') %>
    <%= f.text_field :first_name %>
  </div>

  <div class="input-row">
    <%= f.label I18n.t('models.contact.attributes.email') %>
    <%= f.text_field :email %>
  </div>

  <div class="input-row">
    <%= f.label I18n.t('models.contact.attributes.tel_number') %>
    <%= f.text_field :tel_number %>
  </div>

  <div class="input-row">
    <%= f.label I18n.t('models.contact.attributes.fax_number') %>
    <%= f.text_field :fax_number %>
  </div>

  <div class="input-row">
    <%= f.label I18n.t('models.contact.attributes.address') %>
    <%= f.text_field :address %>
  </div>

  <div class="input-row">
    <%= f.label "所属企業" %>

    <% if @belonging %>
      <%= f.collection_select :id,
        Account.select(:id, :name).order(:name),
        :id,
        :name,
        :selected => @belonging.id %>

    <% else %>
        <%= select_tag 'account_contact[account_id]',
          options_for_select(Account.pluck(:name, :id).unshift(["","none"])) %>
    <% end %>

  </div>

  <div class="content-padded">
    <div class="btn btn-positive btn-block">
      <%= f.submit %>
    </div>
  </div>

  <%= form_cancel_button %>

<% end %>

app/views/contacts/_submenu_bar.html.erb
<div class="content-padded" id="submenu_bar">
  <div class="segmented-control">

    <%= link_to '詳細',
      @contact,
      :class => "control-item",
      :id =>"link_to_show" %>

    <%= link_to '編集履歴',
      history_contact_path(@contact),
      :class => "control-item",
      :id =>"link_to_history" %>

    <%= link_to '編集',
      edit_contact_path(@contact),
      :class => "control-item",
      :id =>"link_to_edit" %>

    <%= link_to '削除',
      @contact,
      method: :delete,
      data: { confirm: 'Are you sure?' } ,
      :class => "control-item",
      :id =>"link_to_delete" %>

  </div>
</div>

app/views/contacts/edit.html.erb
<h5 class="content-padded" id="main-breadcum">
  <%= link_to "メニュー", home_index_path %>
  <%= breadcrumb_seperator %>
  <%= link_to I18n.t('models.contact.name'), contacts_path %>
  <%= breadcrumb_seperator %>
  編集
</h5>

<%= render 'submenu_bar' %>
<%= render 'form' %>

app/views/contacts/history.erb
<%# TODO:ヘルパー化 %>
<h5 class="content-padded" id="main-breadcum">
  <%= link_to "メニュー", home_index_path %>
  <%= breadcrumb_seperator %>
  <%= link_to I18n.t('models.contact.name'), contacts_path %>
  <%= breadcrumb_seperator %>
  編集履歴
</h5>

<%= render 'submenu_bar' %>

<% if @histories.size > 0 %>
  <h5 class="content-padded">
    編集履歴:<%= @histories.size %>件
  </h5>
  <% @histories.each do |history| %>
    <form class="input-group">
      <div class="input-row">
        <label>更新日時</label>
        <input type="text" value="<%= datetime_ymdhm(history.updated_at) %>" readonly="true">
      </div>
      <div class="input-row">
        <label><%= I18n.t('models.contact.attributes.last_name') %></label>
        <input type="text" placeholder="" value="<%= history.last_name %>" readonly="true">
      </div>
      <div class="input-row">
        <label><%= I18n.t('models.contact.attributes.first_name') %></label>
        <input type="text" placeholder=""  value="<%= history.first_name %>" readonly="true">
      </div>
      <div class="input-row">
        <label><%= I18n.t('models.contact.attributes.email') %></label>
        <input type="email" value="<%= history.email %>" readonly="true">
      </div>
      <div class="input-row">
        <label><%= I18n.t('models.contact.attributes.tel_number') %></label>
        <input type="tel" value="<%= history.tel_number %>" readonly="true">
      </div>
      <div class="input-row">
        <label><%= I18n.t('models.contact.attributes.fax_number') %></label>
        <input type="tel" value="<%= history.fax_number %>" readonly="true">
      </div>
      <div class="input-row">
        <label><%= I18n.t('models.contact.attributes.address') %></label>
        <input type="text" value="<%= history.address %>" readonly="true">
      </div>
    </form>
  <% end %>
<% else %>
    <h5 class="content-padded">
      編集履歴はありません
    </h5>
<% end %>

<h5 class="content-padded"></h5>

<%= back_bar %>

app/views/contacts/index.html.erb
<h5 class="content-padded" id="main-breadcum">
  <a href="<%= url_for :controller => 'home' %>">メニュー</a>
  <%= breadcrumb_seperator %>
  連絡先
</h5>

<div class="content-padded">
  <form>
    <input type="text" name="keyword" placeholder="キーワード">
      <button class="btn btn-positive btn-block">
        <%= I18n.t('operate.search') %>
      </button>
  </form>
</div>

<h5 class="content-padded">検索結果:<%= @all_contacts.size %>件</h5>
<div class="content-padded"><%= paginate @contacts %></div>

<ul class="table-view">
  <% @contacts.each do |contact| %>
  <li class="table-view-cell media">
    <a class="navigate-right" href="<%= url_for contact %>" data-transition="slide-in">
      <div class="media-body">
        <%= contact.last_name + " " + contact.first_name %>
      </div>
    </a>
  </li>
  <% end %>
</ul>

<%= link_bar(new_contact_path, I18n.t('operate.new')) %>
<%= link_bar(home_index_path, I18n.t('operate.back')) %>

app/views/contacts/new.html.erb
<h5 class="content-padded" id="main-breadcum">
  <%= link_to "メニュー", home_index_path %>
  <%= breadcrumb_seperator %>
  <%= link_to I18n.t('models.contact.name'), contacts_path %>
  <%= breadcrumb_seperator %>
  <%= I18n.t('operate.new') %>
</h5>

<%= render 'form' %>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<%# TODO:ヘルパー化 %>
<h5 class="content-padded" id="main-breadcum">
  <%= link_to "メニュー", home_index_path %>
  <%= breadcrumb_seperator %>
  <%= link_to I18n.t('models.contact.name'), contacts_path %>
  <%= breadcrumb_seperator %>
  詳細
</h5>

<%= render 'submenu_bar' %>

<%# TODO:フォームが冗長なのできれいにしたい%>
<%= form_for(@contact, html: {class: "input-group"}) do |f| %>
  <div class="input-row">
    <label><%= I18n.t('models.contact.attributes.last_name') %></label>
    <input type="text" placeholder="" value="<%= @contact.last_name %>" readonly="true">
  </div>
  <div class="input-row">
    <label><%= I18n.t('models.contact.attributes.first_name') %></label>
    <input type="text" placeholder=""  value="<%= @contact.first_name %>" readonly="true">
  </div>
  <div class="input-row">
    <label><%= I18n.t('models.contact.attributes.email') %></label>
    <input type="email" value="<%= @contact.email %>" readonly="true">
  </div>
  <div class="input-row">
    <label><%= I18n.t('models.contact.attributes.tel_number') %></label>
    <input type="tel" value="<%= @contact.tel_number %>" readonly="true">
  </div>
  <div class="input-row">
    <label><%= I18n.t('models.contact.attributes.fax_number') %></label>
    <input type="tel" value="<%= @contact.fax_number %>" readonly="true">
  </div>
  <div class="input-row">
    <label><%= I18n.t('models.contact.attributes.address') %></label>
    <input type="text" value="<%= @contact.address %>" readonly="true">
  </div>
  <div class="input-row">
    <label><%= "所属企業" %></label>
    <% if @belonging %>
      <a href="<%= url_for(controller: 'accounts', action: 'show', id: @belonging.id) %>">
        <input type="text" value="<%= @belonging.name if @belonging %>" readonly="true">
      </a>
    <% else %>
      <input type="text" readonly="true">
    <% end %>
  </div>
  <div class="input-row">
    <label>登録日</label>
    <input type="text" value="<%= date_ymd(@contact.created_at) %>" readonly="true">
  </div>
  <div class="input-row">
    <label>最終更新日</label>
    <input type="text" value="<%= date_ymd(@contact.updated_at) %>" readonly="true">
  </div>
</form>
<% end %>

<h5 class="content-padded"></h5>

<%= back_bar %>