config/routes.rb
Rails.application.routes.draw do

  get 'home/index'

  root 'home#index'

  concern :history do
    get :history, :on => :member
  end

  resources :contacts, concerns: :history
  resources :accounts, concerns: :history

  match "*path_does_not_exists" => "errors#raise_action_dispatch_exception", via: :all

end

app/models/account.rb
# == Schema Information
#
# Table name: accounts
#
#  id             :integer          not null, primary key
#  name           :string(255)
#  tel_number     :string(255)
#  fax_number     :string(255)
#  address        :string(255)
#  website        :string(255)
#  representative :string(255)
#  capital        :integer
#  created_at     :datetime
#  updated_at     :datetime
#

class Account < ActiveRecord::Base
  #association---------------------------------------------------------
  has_many :account_histories
  has_many :account_contacts
  has_many :contacts, :through => :account_contacts

  #validation ---------------------------------------------------------
  #TODO:impl validation

  #scope---------------------------------------------------------
  scope :which_this_contact_belongs_to, ->(contact_id) {
    select(:id, :name)
    .includes(:account_contacts)
    .where(account_contacts: {contact_id: contact_id })
  }

end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update, :destroy]
  before_action :set_related_contact, only: [:show, :edit]

  # GET /accounts
  # GET /accounts.json
  def index
    if params[:keyword] && params[:keyword].present?
      @all_accounts = Account.where("name LIKE ?", "%#{params[:keyword]}%")
      @accounts = @all_accounts.page(params[:page])
    else
      @all_accounts = Account.all
      @accounts = @all_accounts.page(params[:page])
    end
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
  end

  def history
    @account = Account.find(params[:id])
    @histories = AccountHistory.of(params[:id])
  end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new(account_params)

    respond_to do |format|
      if @account.save
        format.html { redirect_to @account, notice: 'Account was successfully created.' }
        format.json { render :show, status: :created, location: @account }
      else
        format.html { render :new }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def update

    @account_history = AccountHistory.new(
      account_id: @account.id,
      name: @account.name,
      tel_number: @account.tel_number,
      fax_number: @account.fax_number,
      address: @account.address,
      website: @account.website,
      capital: @account.capital
    )


    respond_to do |format|
      if @account.update(account_params)  && @account_history.save
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_url, notice: 'Account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    def set_related_contact
      @contacts = Contact.includes(:account_contacts).where(account_contacts: { account_id: params[:id] })
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def account_params
      params.require(:account).permit(:name, :tel_number, :fax_number, :address, :website, :representative, :capital)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_form.html.erb
<script>
  function focusOnFirstInput(){
    var e = document.getElementById("contact_last_name")
    e.focus()
  }
  document.body.onload=focusOnFirstInput;
</script>


<% if @account.errors.any? %>
  <div class="card" id="error_explanation">
    <% @account.errors.full_messages.each do |message| %>
      <ul class="table_view">
        <li class="table_view-cell"><%= message %></li>
      </ul>
    <% end %>
  </div>
<% end %>


<%= form_for(@account, html: {class: "input-group"}) do |f| %>

  <div class="input-row">
    <label><%= I18n.t('models.account.attributes.name') %></label>
    <%= f.text_field :name %>
  </div>
  <div class="input-row">
    <label><%= I18n.t('models.account.attributes.tel_number') %></label>
    <%= f.text_field :tel_number %>
  </div>
  <div class="input-row">
    <label><%= I18n.t('models.account.attributes.fax_number') %></label>
    <%= f.text_field :fax_number %>
  </div>
  <div class="input-row">
    <label><%= I18n.t('models.account.attributes.address') %></label>
    <%= f.text_field :address %>
  </div>
  <div class="input-row">
    <label><%= I18n.t('models.account.attributes.website') %></label>
    <%= f.text_field :website %>
  </div>
  <div class="input-row">
    <label><%= I18n.t('models.account.attributes.representative') %></label>
    <%= f.text_field :representative %>
  </div>
  <div class="input-row">
    <label><%= I18n.t('models.account.attributes.capital') %></label>
    <%= f.number_field :capital %>
  </div>

  <div class="content-padded">
    <div class="btn btn-positive btn-block">
      <%= f.submit %>
    </div>
  </div>

  <%= form_cancel_button %>

<% end %>

app/views/accounts/_submenu_bar.html.erb
<div class="content-padded" id="submenu_bar">
  <div class="segmented-control">

    <%= link_to '詳細',
      @account,
      :class => "control-item",
      :id =>"link_to_show" %>

    <%= link_to '編集履歴',
      history_account_path(@account),
      :class => "control-item",
      :id =>"link_to_history" %>

    <%= link_to '編集',
      edit_account_path(@account),
      :class => "control-item",
      :id =>"link_to_edit" %>

    <%= link_to '削除',
      @account,
      method: :delete,
      data: { confirm: 'Are you sure?' } ,
      :class => "control-item",
      :id =>"link_to_delete" %>

  </div>
</div>

app/views/accounts/edit.html.erb
<h5 class="content-padded" id="main-breadcum">
  <%= link_to "メニュー", home_index_path %>
  <%= breadcrumb_seperator %>
  <%= link_to "企業", accounts_path %>
  <%= breadcrumb_seperator %>
  編集
</h5>

<%= render 'submenu_bar' %>
<%= render 'form' %>

app/views/accounts/history.erb
<h5 class="content-padded" id="main-breadcum">
  <%= link_to "メニュー", home_index_path %>
  <%= breadcrumb_seperator %>
  <%= link_to "企業", accounts_path %>
  <%= breadcrumb_seperator %>
  編集履歴
</h5>

<%= render 'submenu_bar' %>

<% if @histories.size > 0 %>
  <h5 class="content-padded">
    編集履歴:<%= @histories.size %>件
  </h5>
  <% @histories.each do |history| %>
    <form class="input-group">
      <div class="input-row">
        <label>更新日時</label>
        <input type="text" value="<%= datetime_ymdhm(history.updated_at) %>" readonly="true">
      </div>
      <div class="input-row">
        <label><%= I18n.t('models.account.attributes.name') %></label>
        <input type="text" placeholder="" value="<%= history.name %>" readonly="true">
      </div>
      <div class="input-row">
        <label><%= I18n.t('models.account.attributes.tel_number') %></label>
        <input type="tel" value="<%= history.tel_number %>" readonly="true">
      </div>
      <div class="input-row">
        <label><%= I18n.t('models.account.attributes.fax_number') %></label>
        <input type="tel" value="<%= history.fax_number %>" readonly="true">
      </div>
      <div class="input-row">
        <label><%= I18n.t('models.account.attributes.address') %></label>
        <input type="text" value="<%= history.address %>" readonly="true">
      </div>
      <div class="input-row">
        <label><%= I18n.t('models.account.attributes.website') %></label>
        <input type="text" value="<%= history.website %>" readonly="true">
      </div>
      <div class="input-row">
        <label><%= I18n.t('models.account.attributes.representative') %></label>
        <input type="text" value="<%= history.representative %>" readonly="true">
      </div>
      <div class="input-row">
        <label><%= I18n.t('models.account.attributes.capital') %></label>
        <input type="text" value="<%= number_to_currency(history.capital) %>" readonly="true">
      </div>
    </form>
  <% end %>
<% else %>
    <h5 class="content-padded">
      編集履歴はありません
    </h5>
<% end %>

<%= back_bar %>

app/views/accounts/index.html.erb
<h5 class="content-padded" id="main-breadcum">
  <a href="<%= url_for :controller => 'home' %>">メニュー</a>
  <%= breadcrumb_seperator %>
  企業
</h5>

<div class="content-padded">
  <form>
    <input type="text" name="keyword" placeholder="キーワード">
      <button class="btn btn-positive btn-block">
        <%= I18n.t('operate.search') %>
      </button>
  </form>
</div>

<h5 class="content-padded">検索結果:<%= @all_accounts.size %>件</h5>
<div class="content-padded"><%= paginate @accounts %></div>

<ul class="table-view">
  <% @accounts.each do |account| %>
  <li class="table-view-cell media">
    <a class="navigate-right" href="<%= url_for account %>" data-transition="slide-in">
      <div class="media-body">
        <%= account.name %>
      </div>
    </a>
  </li>
  <% end %>
</ul>

<br>

<%= link_bar new_account_path, I18n.t('operate.new') %>
<%= link_bar(home_index_path, I18n.t('operate.back')) %>

app/views/accounts/new.html.erb
<h5 class="content-padded" id="main-breadcum">
  <%= link_to "メニュー", home_index_path %>
  <%= breadcrumb_seperator %>
  <%= link_to "企業", accounts_path %>
  <%= breadcrumb_seperator %>
  新規
</h5>

<%= render 'form' %>

app/views/accounts/show.html.erb
<p id="notice"><%= notice %></p>

<h5 class="content-padded" id="main-breadcum">
  <%= link_to "メニュー", home_index_path %>
  <%= breadcrumb_seperator %>
  <%= link_to "企業", accounts_path %>
  <%= breadcrumb_seperator %>
  詳細
</h5>

<%= render 'submenu_bar' %>

<%= form_for(@account, html: {class: "input-group"}) do |f| %>

  <div class="input-row">
    <label><%= I18n.t('models.account.attributes.name') %></label>
    <%= f.text_field :name, :readonly => true %>
  </div>

  <div class="input-row">
    <label><%= I18n.t('models.account.attributes.tel_number') %></label>
    <%= f.text_field :tel_number, :readonly => true %>
  </div>

  <div class="input-row">
    <label><%= I18n.t('models.account.attributes.fax_number') %></label>
    <%= f.text_field :fax_number, :readonly => true %>
  </div>

  <div class="input-row">
    <label><%= I18n.t('models.account.attributes.address') %></label>
    <%= f.text_field :address, :readonly => true %>
  </div>

  <div class="input-row">
    <label><%= I18n.t('models.account.attributes.website') %></label>
    <%= f.text_field :website, :readonly => true %>
  </div>

  <div class="input-row">
    <label><%= I18n.t('models.account.attributes.representative') %></label>
    <%= f.text_field :representative, :readonly => true %>
  </div>

  <div class="input-row">
    <label><%= I18n.t('models.account.attributes.capital') %></label>
    <%= f.text_field :capital,
      :value => number_to_currency(@account.capital),
      :readonly => true %>
  </div>

  <div class="input-row">
    <label>登録日</label>
    <input type="text" value="<%= date_ymd(@account.created_at) %>" readonly="true">
  </div>

  <div class="input-row">
    <label>最終更新日</label>
    <input type="text" value="<%= date_ymd(@account.updated_at) %>" readonly="true">
  </div>
<% end %>

<% if @contacts.size > 0 %>

  <h5 class="content-padded">
    この企業に所属している連絡先:<%= @contacts.size %>件
  </h5>

  <ul class="table-view">
    <% @contacts.each do |contact| %>
      <li class="table-view-cell media">
        <a class="navigate-right" href="<%= url_for contact %>" data-transition="slide-in">
          <div class="media-body">
            <%= contact.last_name + " " + contact.first_name %>
          </div>
        </a>
      </li>
    <% end %>
  </ul>

<% end %>

<%= link_to 'この企業の連絡先を新規登録',
  new_contact_path(account_id: @account.id) %>

<%= back_bar %>